Database
NoBetterThan97/tweetsearch-api pull request #3
Opened 2016-11-10 06:15 UTC by Leoli0320

2016-11-11 02:30 UTC, cyhsutw requested changes
@Leoli0320 thanks for this pull request.

I pull this branch and run `rake db:migrate` locally, and it isn't working.

I think you'll need to move `db/migration/001_tweets_create.rb` to `db/migrations/001_tweets_create.rb` (you're missing an `s`).

Another minor nit, could you run `bundle install` and commit the new `Gemfile.lock`?

2016-11-11 02:30 UTC, cyhsutw commented on db/migration/001_tweets_create.rb
> +      String :create_time
Can we change this to `datetime` data type? 
Also, I would prefer the name of this field to be `created_at`.

2016-11-11 05:51 UTC, Leoli0320 commented
@cyhsutw  thanks for point out the problems! I'm very appreciated.
I correct the error that you found. 
Could you help me check it again?
Thanks!

2017-01-05 12:33 UTC, cyhsutw commented
Closing this as we are not going to maintain this API.

2017-01-05 12:33 UTC, closed without merging